name: Cloud Foundry Auto Start

on:
  schedule:
    - cron: '50/10 23 * * *'  # 北京时间7:50-8:30每10分钟一次（UTC时间23:50-0:30）
  workflow_dispatch:       # 允许手动触发

jobs:
  start-cf-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Debug environment variables
      run: |
        echo "CF_USERNAME: ${{ secrets.CF_USERNAME && '已设置' || '未设置' }}"
        echo "CF_PASSWORD: ${{ secrets.CF_PASSWORD && '已设置' || '未设置' }}"
        echo "CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT && '已设置' || '未设置' }}"
        echo "CF_ORG: ${{ secrets.CF_ORG && '已设置' || '未设置' }}"
        echo "CF_APPS: ${{ secrets.CF_APPS && '已设置' || '未设置' }}"

    - name: Run Cloud Foundry Auto Start
      run: python cf_auto_start.py
      env:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_APPS: ${{ secrets.CF_APPS }}
